
export const GALLEON_IN_SICKLES = 17;
export const SICKLE_IN_KNUTS = 29;
export const GALLEON_IN_KNUTS = GALLEON_IN_SICKLES * SICKLE_IN_KNUTS; // 493

export interface Currency {
  galleons: number;
  sickles: number;
  knuts: number;
}

/**
 * Converts a total number of Knuts into a canonical representation of
 * Galleons, Sickles, and Knuts. This can also convert a non-canonical
 * currency object by first converting it to total knuts.
 * @param totalKnutsOrCurrency The total amount in Knuts or a non-canonical Currency object.
 * @returns An object with the amount of galleons, sickles, and knuts.
 */
export function knutsToCanonical(totalKnutsOrCurrency: number | Currency): Currency {
  let totalKnuts: number;

  if (typeof totalKnutsOrCurrency === 'number') {
    totalKnuts = totalKnutsOrCurrency;
  } else {
    totalKnuts = currencyToKnuts(totalKnutsOrCurrency);
  }
  
  if (isNaN(totalKnuts)) {
    return { galleons: 0, sickles: 0, knuts: 0 };
  }
  
  let remainingKnuts = totalKnuts;

  const galleons = Math.floor(remainingKnuts / GALLEON_IN_KNUTS);
  remainingKnuts %= GALLEON_IN_KNUTS;

  const sickles = Math.floor(remainingKnuts / SICKLE_IN_KNUTS);
  remainingKnuts %= SICKLE_IN_KNUTS;

  return {
    galleons,
    sickles,
    knuts: remainingKnuts,
  };
}


/**
 * Converts a Currency object (Galleons, Sickles, Knuts) into a single
 * total value in Knuts.
 * @param currency An object with galleons, sickles, and knuts properties.
 * @returns The total value in Knuts.
 */
export function currencyToKnuts(currency: Partial<Currency>): number {
  const { galleons = 0, sickles = 0, knuts = 0 } = currency;
  return (galleons * GALLEON_IN_KNUTS) + (sickles * SICKLE_IN_KNUTS) + knuts;
}

export const PAYMENT_REASONS = [
    "für Butterbier",
    "Runde Feuerwhiskey",
    "Schulden bei den Weasleys",
    "Neuer Besen",
    "Zutaten für Vielsafttrank",
    "Wettgewinn vom Quidditch-Spiel",
    "Bestechungsgeld für Filch",
    "Eine Kiste Bertie Botts Bohnen",
    "Reisekosten für den Fahrenden Ritter",
    "Reparatur für den kaputten Zauberstab",
    "Eintritt für die Heulende Hütte",
    "Ein neues Exemplar von 'Phantastische Tierwesen'",
    "Kaution für Hagrid",
    "Spende für S.P.E.W.",
    "Ein paar Schokofrösche",
    "Beitrag zur nächsten DA-Sitzung",
    "Eine Federkiel-Lizenz",
    "Nachhilfe in Verwandlung",
    "Ein Heuler für Malfoy",
    "Karte des Rumtreibers",
    "Dein Anteil am Honigtopf-Raubzug",
    "Die neuesten Zauberscherze",
    "Ein Abo vom Tagespropheten",
    "Rückzahlung für die Butterbier-Runde",
    "Neuer Umhang von Madam Malkin's",
    "Kürbissaft für alle",
    "Ein Päckchen Zischende Wissbies",
    "Pflege für einen Hippogreif",
    "Eine Flasche Veritaserum (nicht fragen)",
    "Ein Denkarium zum Ausleihen",
    "Magische Tiernahrung",
    "Reparaturkosten für das fliegende Auto",
    "Schweineohren von den Drei Besen",
    "Gehalt für den Hauself",
    "Eine seltene Alraune",
    "Investition in einen portablen Sumpf",
    "Geld für den nächsten Hogsmeade-Ausflug",
    "Ein neues Paar Drachenleder-Handschuhe",
    "Spende an den Orden des Phönix",
    "Ein neuer Satz Zaubertrank-Fläschchen",
    "Ein magisches Schachspiel",
    "Erinnerungsmich-Ersatz",
    "Eine Kiste Knallbonbons",
    "Bestellung bei Eeylops Eulenkaufhaus",
    "Ein seltener Zaubertrank-Aufsatz",
    "Die Pflege von Krätze",
    "Ein Pfund Mondkalb-Dung",
    "Eine Schachtel Lakritz-Zauberstäbe",
    "Ersatz für den explodierenden Kessel",
    "Ein verfluchtes Halsband (Scherz!)",
    "Dein Geburtstaggeschenk",
    "Eine Schachtel Würg Riegel",
    "Für ein paar Verlängerbare Ohren",
    "Investition in Kanarienvogel-Kekse",
    "Peruanisches Instant-Finsternispulver",
    "Ein Päckchen Nasch-und-Schwänz-Leckereien",
    "Garantierte 10-Sekunden-Pickel-Entferner",
    "Ein Liebestrank (für Forschungszwecke, natürlich)",
    "Wiederauffüllbarer Vorrat an Kotzbomben",
    "Ein Set essbarer Dunkler Male",
    "Für einen patentierten Tagtraumzauber",
    "Ein Kopf-ab-Hut, nur zum Spaß",
    "Ein Wunderhexen-Zauber-Set",
    "Geld für den Scherzartikelladen",
    "Eine Lieferung Fressanfall-Fudge",
    "Einkaufstour bei Honigtopf",
    "Ein paar Pints in den Drei Besen",
    "Neuer Kessel von Potage's",
    "Einkauf bei Flourish & Blotts",
    "Neue Feder von Scrivenshaft's",
    "Ein Besuch bei Zonko's Scherzartikelladen",
    "Geld für Madam Puddifoot's Teesalon",
    "Eulenleckerlis von Eeylops",
    "Die neueste Ausgabe des Tagespropheten",
    "Eine Kugel bei Florean Fortescue's Eissalon",
    "Neue Roben von Madam Malkin's",
    "Ein Besuch im Tropfenden Kessel",
    "Gringotts Bearbeitungsgebühr",
    "Besenpolitur-Set",
    "Tickets für das nächste Chudley Cannons Spiel",
    "Wetteinsatz für das Gryffindor vs. Slytherin Spiel",
    "Neuer Satz Quidditch-Handschuhe",
    "Reparatur des Klatschers",
    "Ein Poster von Viktor Krum",
    "Team-Beitrag für neue Umhänge",
    "Ein Quidditch-Almanach",
    "Heiltrank für nach dem Training",
    "Ein Ticket für die Quidditch-Weltmeisterschaft",
    "Futter für einen Kniesel",
    "Ein Halsband für Fang",
    "Drachenfutter (streng geheim)",
    "Eine neue Decke für Hedwig's Käfig",
    "Ein Buch über die Pflege von Hippogreifen",
    "Bezahlung für die De-Gnomisierung des Gartens",
    "Ein Sack voll Niffler-Futter",
    "Bowtruckle-Zweige",
    "Ein Terrarium für einen Schrumpffüßler",
    "Salamander-Futter",
    "Nachhilfe in Zaubertränke bei Slughorn",
    "Ein neuer Satz Phiolen",
    "Pergament und Tinte",
    "Eine Ausgabe von 'Verteidigung für Fortgeschrittene'",
    "Beitrag für den Duellierclub",
    "Gebühr für die Apparierprüfung",
    "Ein neues Teleskop für Astronomie",
    "Kräuterkunde-Handschuhe",
    "Ein Exemplar von 'Geschichte der Zauberei'",
    "Punkte für den Hauspokal kaufen (versuchen wir's mal)",
    "Schweigegeld für Peeves",
    "Passwort für die fette Dame vergessen",
    "Ein Beitrag zum 'Wir-hassen-Umbridge'-Fond",
    "Ein Portschlüssel nach Hause",
    "Ein neues Paar Socken für Dobby",
    "Gebühr für die Bibliothek (Buch war überfällig)",
    "Ein magisches Amulett gegen Nargel",
    "Eine Flasche Felix Felicis (sehr teuer)",
    "Ein neuer Zeitumkehrer (der alte ist kaputt)",
    "Ein Gobstone-Set",
    "Zauberer-Schach-Wetteinsatz",
    "Eine Ausgabe des Klitterers",
    "Finanzierung für die Suche nach dem Schrumpfhörnigen Schnarchkackler",
    "Ein Geschenk für Professor McGonagall",
    "Ein Heuler an meine Eltern (Porto)",
    "Bestechung für einen Slytherin, damit er schweigt",
    "Ein Beruhigungstrank für die ZAGs",
    "Bezahlung für die Entfernung eines Flederwicht-Fluchs",
    "Ein Zauber, um Socken zu sortieren",
    "Ein Abonnement für 'Hexenwoche'",
    "Ein Selbst-umrührender Kessel",
    "Ein Set Explodierender Snap",
    "Eine Spende für St. Mungo's",
    "Rückzahlung einer verlorenen Wette",
    "Geld für den nächsten Streich",
    "Ein neuer Tarnumhang (der alte hat ein Loch)",
    "Ein seltener Autogramm von Gilderoy Lockhart",
    "Ein magischer Kalender, der Termine schreit",
    "Ein Muggel-Artefakt für Mr. Weasley",
    "Eine Kiste mit heulenden Süßigkeiten",
    "Ein Zauber, der die Hausaufgaben macht",
    "Eine Flasche Odgen's Old Firewhisky",
    "Ein Päckchen Droobles Bester Blaskaugummi",
    "Ein Geschenk für den Hausgeist",
    "Reparatur eines zerbrochenen Erinner-michs",
    "Einladung zum Weihnachtsball (plus eins)",
    "Geld für einen neuen Familiar",
    "Ein Zauberbuch mit leeren Seiten (Scherz!)",
    "Beitrag für die nächste Party im Gemeinschaftsraum",
    "Ein magisches Vorhängeschloss für mein Tagebuch",
    "Eine Schachtel Säure-Knaller",
    "Ein Zauber, der Gemüse wie Süßigkeiten schmecken lässt",
    "Eine Karte für das Konzert der Schwestern des Schicksals",
    "Ein Set selbststrickender Nadeln",
    "Eine verzauberte Schneekugel von Hogsmeade",
    "Geld für einen Ausflug in die Winkelgasse",
    "Ein Päckchen singender Lebkuchenmänner",
    "Ein Amulett zum Schutz vor Werwölfen (nur für den Fall)",
    "Ein verzauberter Kompass, der zum Kühlschrank führt",
    "Ein Kissen, das einem Schlaflieder vorsingt",
    "Ein magisches Pflaster, das Wunden sofort heilt",
    "Ein Zauber, der verlorene Gegenstände findet",
    "Ein Set unsichtbarer Tinte",
    "Ein verzaubertes Lesezeichen, das die Geschichte vorliest",
    "Ein magischer Federkiel, der nicht kleckst",
    "Ein Set schwebender Kerzen für mein Zimmer",
    "Ein Zauber, der die Schuhe selbst bindet",
    "Eine Flasche Elfenwein",
    "Ein verzauberter Regenschirm, der einen immer trocken hält",
    "Ein magischer Fön, der die Haare in Sekunden stylt",
    "Ein Set selbst-nachfüllender Tintenfässer",
    "Eine Packung Kaugummi, das nie seinen Geschmack verliert",
    "Ein verzauberter Spiegel, der Komplimente macht",
    "Ein magischer Notizblock, der Gedanken aufschreibt",
    "Ein Set magischer Würfel, die immer Glück bringen",
    "Ein Zauber, der die Wäsche selbst wäscht und faltet",
    "Eine verzauberte Teetasse, die nie kalt wird",
    "Ein magischer Wecker, der einen sanft weckt",
    "Ein Set selbst-schreibender Federn für Notizen",
    "Eine magische Gießkanne, die Pflanzen perfekt bewässert",
    "Ein verzauberter Pinsel, der von alleine malt",
    "Ein magischer Türklopfer, der Witze erzählt",
    "Ein Set schwebender Lichterketten",
    "Ein verzauberter Schal, der immer die perfekte Temperatur hat",
    "Eine magische Spieluhr mit beruhigenden Melodien",
    "Ein Zauber, der den Boden selbst schrubbt",
    "Ein verzauberter Stuhl, der sich dem Rücken anpasst",
    "Ein magischer Kalender, der an Geburtstage erinnert",
    "Ein Set selbst-aktualisierender Karten",
    "Eine magische Duftkerze, die den Lieblingsduft verströmt",
    "Ein verzauberter Teppich, der Flecken abweist",
    "Ein magischer Fotorahmen mit bewegten Bildern",
    "Ein Set selbst-mischender Spielkarten",
    "Eine verzauberte Kaffeemaschine, die den perfekten Kaffee kocht",
    "Ein magischer Toaster, der das Brot nie verbrennt",
    "Ein Set selbst-reinigender Fenster",
    "Ein verzauberter Kleiderschrank, der das Outfit des Tages vorschlägt",
    "Ein magischer Mülleimer, der sich selbst leert",
    "Ein Set schwebender Bücherregale",
    "Eine verzauberte Türklingel mit verschiedenen Melodien",
    "Ein magischer Schlüssel, der jedes Schloss öffnet (fast)",
    "Ein Set selbst-aufblasender Luftballons",
    "Eine verzauberte Hängematte für den Gemeinschaftsraum",
    "Ein magischer Radiergummi, der keine Spuren hinterlässt",
    "Ein Set selbst-kühlender Getränkehalter",
    "Eine verzauberte Blumenvase, die Blumen ewig frisch hält",
    "Ein magischer Notenständer, der die Seiten umblättert",
    "Ein Set selbst-leuchtender Sterne für die Decke",
    "Eine verzauberte Nähmaschine, die von alleine näht",
    "Ein magischer Fächer, der kühle Brisen erzeugt",
    "Ein Set selbst-organisierender Schubladen",
    "Eine verzauberte Leseleuchte, die die Augen schont",
    "Ein magischer Weinkühler",
    "Ein Set selbst-schärfender Messer für die Küche",
    "Eine verzauberte Picknickdecke, die Insekten fernhält",
    "Ein magischer Komposter, der Abfall sofort in Erde verwandelt",
    "Ein Set selbst-wachsender Kräuter für die Küche",
    "Eine verzauberte Bratpfanne, die das Essen nicht anbrennen lässt",
    "Ein magischer Salz- und Pfefferstreuer, der nie leer wird",
    "Ein Set selbst-reinigender Pinsel",
    "Eine verzauberte Staffelei, die das Bild festhält",
    "Ein magisches Skizzenbuch, das Ideen zum Leben erweckt",
    "Ein Set selbst-stimmender Musikinstrumente",
    "Eine verzauberte Harfe, die von alleine spielt",
    "Ein magisches Metronom, das den Takt hält",
    "Ein Set selbst-schreibender Notenblätter",
    "Eine verzauberte Flöte mit bezaubernden Klängen",
    "Ein magisches Schlagzeug, das im Takt bleibt",
    "Ein Set selbst-tanzender Schuhe",
    "Eine verzauberte Jukebox mit allen Lieblingsliedern",
    "Ein magischer Plattenspieler mit unendlicher Plattenauswahl",
    "Ein Set selbst-aufbauender Zelte für Campingausflüge",
    "Eine verzauberte Angelrute, die immer Fische fängt",
    "Ein magisches Lagerfeuer, das nie ausgeht",
    "Ein Set selbst-wärmender Socken für kalte Nächte",
    "Eine verzauberte Thermoskanne, die Getränke ewig heiß oder kalt hält",
    "Ein magischer Rucksack mit unendlich viel Platz",
    "Ein Set selbst-findender Wanderkarten",
    "Eine verzauberte Laterne, die den Weg erhellt",
    "Ein magischer Schlafsack, der immer bequem ist",
    "Ein Set selbst-aufstellender Hängematten",
    "Eine verzauberte Wasserflasche, die sich selbst reinigt und auffüllt",
    "Ein magischer Kompass, der zu Abenteuern führt",
    "Ein Set selbst-trocknender Handtücher",
    "Eine verzauberte Sonnencreme, die perfekten Schutz bietet",
    "Ein magischer Sonnenschirm, der Schatten spendet",
    "Ein Set selbst-aufblasender Schwimmtiere",
    "Eine verzauberte Strandtasche mit allem, was man braucht",
    "Ein magischer Sandkasten mit unendlich viel Sand",
    "Ein Set selbst-bauender Sandburgen",
    "Eine verzauberte Muschel, die das Meeresrauschen wiedergibt",
    "Ein magisches Fernglas, das in die Ferne blicken lässt",
    "Ein Set selbst-fahrender Koffer",
    "Eine verzauberte Reiseapotheke mit allen Heilmitteln",
    "Ein magischer Universalübersetzer",
    "Ein Set selbst-stempelnder Postkarten",
    "Eine verzauberte Kamera, die die besten Momente festhält",
    "Ein magisches Reisetagebuch, das Erlebnisse aufzeichnet",
    "Ein Set selbst-packender Kofferorganizer",
    "Eine verzauberte Nackenrolle für bequemes Reisen",
    "Ein magischer Stadtplan, der den Weg weist",
    "Ein Set selbst-findender Souvenirs",
    "Eine verzauberte Souvenirtasse, die das Lieblingsgetränk enthält",
    "Ein magischer Schlüsselanhänger, der verlorene Schlüssel findet",
    "Ein Set selbst-schließender Reißverschlüsse",
    "Eine verzauberte Geldbörse, die nie leer wird (Wunschdenken)",
    "Ein magischer Pass, der alle Grenzen öffnet",
    "Ein Set selbst-erneuerender Flugtickets",
    "Eine verzauberte Sonnenbrille, die die Welt bunter macht",
    "Ein magischer Hut, der vor Sonne und Regen schützt",
    "Ein Set selbst-kühlender Kleidung für heiße Tage",
    "Eine verzauberte Jacke, die sich dem Wetter anpasst",
    "Ein magischer Schal, der vor Kälte schützt",
    "Ein Set selbst-wärmender Handschuhe",
    "Eine verzauberte Mütze, die nie vom Kopf fällt",
    "Ein magischer Regenschirm, der sich selbst aufspannt und schließt",
    "Ein Set selbst-reinigender Schuhe",
    "Eine verzauberte Tasche mit unzähligen Fächern",
    "Ein magischer Gürtel, der sich der Taille anpasst",
    "Ein Set selbst-bügelnder Hemden",
    "Eine verzauberte Krawatte, die sich selbst bindet",
    "Ein magischer Anzug, der immer perfekt sitzt",
    "Ein Set selbst-polierender Schuhe",
    "Eine verzauberte Uhr, die die Zeit verlangsamen kann",
    "Ein magisches Armband, das Glück bringt",
    "Ein Set selbst-wechselnder Ohrringe",
    "Eine verzauberte Halskette, die im Dunkeln leuchtet",
    "Ein magischer Ring, der die Stimmung anzeigt",
    "Ein Set selbst-lackierender Fingernägel",
    "Ein verzauberter Lippenstift, der die Farbe wechselt",
    "Ein magischer Pinsel, der das perfekte Make-up zaubert",
    "Ein Set selbst-pflegender Hautcremes",
    "Eine verzauberte Haarbürste, die Knoten löst",
    "Ein magischer Spiegel, der die Zukunft zeigt (vielleicht)",
    "Ein Set selbst-schneidender Haarscheren",
    "Ein verzauberter Rasierer, der nie stumpf wird",
    "Ein magisches Parfüm, das unwiderstehlich macht",
    "Ein Set selbst-reinigender Zahnspangen",
    "Eine verzauberte Zahnbürste, die perfekt putzt",
    "Ein magischer Zahnstocher, der nie bricht",
    "Ein Set selbst-erneuerender Kontaktlinsen",
    "Eine verzauberte Brille, die nie beschlägt",
    "Ein magisches Hörgerät, das alles hört",
    "Ein Set selbst-schreibender Rezepte",
    "Eine verzauberte Kochschürze, die sauber bleibt",
    "Ein magisches Kochbuch mit unendlichen Rezepten",
    "Ein Set selbst-schälender Kartoffeln",
    "Eine verzauberte Küchenmaschine, die alles kann",
    "Ein magischer Ofen, der die perfekte Temperatur hält",
    "Ein Set selbst-spülender Töpfe und Pfannen",
    "Eine verzauberte Spülmaschine, die das Geschirr trocknet und einräumt",
    "Ein magischer Kühlschrank, der sich selbst auffüllt",
    "Ein Set selbst-sortierender Gewürze",
    "Eine verzauberte Kaffeetasse, die nie umfällt",
    "Ein magischer Teller, der das Essen warm hält",
    "Ein Set selbst-faltender Servietten",
    "Eine verzauberte Tischdecke, die sich selbst reinigt",
    "Ein magischer Stuhl, der immer bequem ist",
    "Ein Set selbst-dimmender Lichter",
    "Eine verzauberte Fernbedienung, die nie verloren geht",
    "Ein magischer Fernseher, der alle Wünsche erfüllt",
    "Ein Set selbst-ladender Batterien",
    "Eine verzauberte Steckdose, die immer funktioniert",
    "Ein magisches Ladekabel, das nie bricht",
    "Ein Set selbst-aktualisierender Software",
    "Eine verzauberte Maus, die perfekt in der Hand liegt",
    "Ein magischer Drucker, der nie Papierstau hat",
    "Ein Set selbst-schreibender Stifte",
    "Eine verzauberte Tastatur, die fehlerfrei tippt",
    "Ein magischer Bildschirm, der die Augen schont",
    "Ein Set selbst-organisierender Ordner",
    "Eine verzauberte Festplatte mit unendlich viel Speicherplatz",
    "Ein magischer USB-Stick, der nie verloren geht",
    "Ein Set selbst-löschender Spam-Mails",
    "Eine verzauberte Firewall, die alle Viren abwehrt",
    "Ein magisches Antivirenprogramm, das unbesiegbar ist",
    "Ein Set selbst-lernender Algorithmen",
    "Eine verzauberte Suchmaschine, die alle Antworten kennt",
    "Ein magisches soziales Netzwerk, das nur positive Nachrichten anzeigt",
    "Ein Set selbst-erstellender Playlists",
    "Eine verzauberte Musik-App, die den perfekten Song findet",
    "Ein magischer Kopfhörer mit perfektem Klang",
    "Ein Set selbst-synchronisierender Geräte",
    "Eine verzauberte Cloud, die unendlich viel Speicherplatz bietet",
    "Ein magisches Backup, das nie fehlschlägt",
    "Ein Set selbst-reparierender Geräte",
    "Eine verzauberte Garantie, die ewig gilt",
    "Ein magischer Kundenservice, der immer erreichbar ist",
    "Ein Set selbst-lösender Probleme",
    "Eine verzauberte Gebrauchsanweisung, die verständlich ist",
    "Ein magisches Werkzeug, das alles reparieren kann",
    "Ein Set selbst-bohrender Schrauben",
    "Eine verzauberte Leiter, die immer stabil ist",
    "Ein magischer Hammer, der nie daneben schlägt",
    "Ein Set selbst-findender Nägel",
    "Eine verzauberte Säge, die perfekt schneidet",
    "Ein magischer Schraubenzieher, der alle Schrauben passt",
    "Ein Set selbst-haltender Dübel",
    "Eine verzauberte Wasserwaage, die immer gerade ist",
    "Ein magischer Zollstock, der nie bricht",
    "Ein Set selbst-klebender Klebebänder",
    "Eine verzauberte Farbe, die nie tropft",
    "Ein magischer Pinsel, der keine Haare verliert",
    "Ein Set selbst-abdeckender Folien",
    "Eine verzauberte Tapete, die sich selbst anbringt",
    "Ein magischer Teppich, der fliegt (oder auch nicht)",
    "Ein Set selbst-verlegender Fliesen",
    "Eine verzauberte Fugenmasse, die nie schimmelt",
    "Ein magischer Rasenmäher, der von alleine mäht",
    "Ein Set selbst-wässernder Blumen",
    "Eine verzauberte Heckenschere, die perfekt schneidet",
    "Beitrag für die 'Wer kann am längsten als Teekanne sitzen bleiben'-Wette",
    "Anzahlung für einen unsichtbaren Goldfisch",
    "Gebühr für professionelles Spuken (Stufe 3 Geist)",
    "Rückerstattung für den Schrumpftrank, der meine Katze riesig gemacht hat",
    "Dein Anteil am 'Wir tun so, als wären wir Statuen im Park'-Geschäft",
    "Geld für das Patent eines selbstrührenden Kessels, der Witze erzählt",
    "Bestechungsgeld für den Hauself, damit er nicht verrät, wer die Kekse gegessen hat",
    "Miete für das Baumhaus (inklusive Eichhörnchen-Concierge)",
    "Eine Runde 'Find den Niffler' im Gemeinschaftsraum",
    "Lizenzgebühr für die Nutzung meines patentierten Fluchworts",
    "Kosten für die psychologische Betreuung meines verfluchten Gartenzwergs",
    "Sponsoring für das professionelle Gobstone-Team 'Die rollenden Steine'",
    "Abo für 'Zauberer-Woche', die Klatsch- und Tratschzeitschrift",
    "Rückzahlung für das Buch 'Wie man Freunde gewinnt und Leute verhext'",
    "Ein Pfund Drachenschuppenpolitur",
    "Beitrag zum Kauf eines gebrauchten fliegenden Teppichs (hat ein paar Löcher)",
    "Kursgebühr für 'Verteidigung gegen dunkle Künste... und nervige Nachbarn'",
    "Ein Dutzend selbstschreibender Federn, die nur Komplimente schreiben",
    "Reparatur des Zeitumkehrers, der in der Waschmaschine war",
    "Ein Fass Met für die nächste Hauselfen-Gewerkschaftssitzung",
    "Bußgeld für illegales Apparieren in einer Muggel-Telefonzelle",
    "Ein Set magischer Socken, die immer paarweise bleiben",
    "Kosten für die Entfluchung meines Toasters (er spuckt jetzt nur noch Waffeln)",
    "Ein Ticket für das Konzert der 'Schwestern des Schicksals' (Backstage-Pässe!)",
    "Anzahlung für eine maßgeschneiderte Heulende Hütte (weniger Heulen, mehr WLAN)",
    "Ein Glas eingelegte Schrumpfköpfe (rein dekorativ, versprochen)",
    "Futter für meinen Hippogreif (er mag nur Sushi)",
    "Ein Set 'Erweiterbare Ohren', um die Nachbarn zu belauschen",
    "Rückzahlung für die Wette, dass Lockhart einen ganzen Satz ohne 'Ich' sagen kann",
    "Ein magisches Erste-Hilfe-Set für explodierende Snap-Unfälle",
    "Gebühr für die Mitgliedschaft im 'Club der anonymen Werwölfe'",
    "Ein Päckchen 'Nasch-und-Schwänz-Leckereien' für den nächsten Montag",
    "Versicherung für meinen Besen (gegen Drachen und Blitze)",
    "Ein verzauberter Kompass, der immer zum nächsten Pub zeigt",
    "Geld für einen Sprachkurs in Mermish (Wassersprachen)",
    "Ein verfluchtes Schachspiel, bei dem die Figuren beleidigend werden",
    "Kosten für die Beseitigung eines portablen Sumpfes aus meinem Schlafzimmer",
    "Ein Set selbst-nachfüllender Tintenfässer (Geschmacksrichtung: Himbeere)",
    "Bestellung bei 'Weasleys Zauberhafte Zauberscherze' - die große Box",
    "Ein persönlicher Wetterzauber (Sonnenschein über meinem Schreibtisch)",
    "Anzahlung für einen Phönix (Warteliste: 300 Jahre)",
    "Ein Kurs in 'Kreatives Fluchen für Anfänger'",
    "Ein Dutzend Schokofrösche (nur die seltenen Karten, bitte)",
    "Bußgeld für das Parken meines Besens im Halteverbot",
    "Ein selbst-bügelndes Hemd für das nächste Ministeriums-Meeting",
    "Rückerstattung für den Liebestrank, der auf die Katze gewirkt hat",
    "Ein Set magischer Würfel, die immer eine 6 würfeln (nicht schummeln!)",
    "Ein Glas Einhornschweiß (für glänzendes Haar, sagt man)",
    "Beitrag für die 'Rettet die Hauselfen'-Stiftung (S.P.E.W.)",
    "Ein verzauberter Notizbuch, das meine Gedanken stiehlt und Bestseller schreibt",
    "Gebühr für die Reinigung meines Umhangs nach einem Tintenfisch-Angriff im See",
    "Miete für den Besenschrank unter der Treppe",
    "Kosten für die Entlausung meines Basilisken",
    "Ein Abo für 'Der Tagesprophet', aber nur die Comics",
    "Rückzahlung für die Wette, dass ich einen ganzen Kürbissaft-Krug exen kann",
    "Ein neues Gehirn für den Irrwicht im Schrank",
    "Beitrag zur Party-Kasse des Gemeinschaftsraums",
    "Ein Päckchen Bertie Botts Bohnen (bitte keine Ohrenschmalz-Geschmack)",
    "Geld für die Reparatur des kaputten Verschwindekabinetts",
    "Ein Ticket für den Fahrenden Ritter (inklusive Reisekrankheits-Trank)",
    "Bestechung für den Ghul auf dem Dachboden, damit er leiser ist",
    "Ein neuer Satz Gobstones (die alten spucken nicht mehr)",
    "Kursgebühr für 'Wie man einen Drachen erzieht (oder es zumindest überlebt)'",
    "Ein magischer Türsteher für mein Zimmer (Passwort: 'Fidelius')",
    "Futter für meine fleischfressende Pflanze (sie mag Steak)",
    "Ein Set selbst-schreibender Notizen, die sich an alles erinnern",
    "Bußgeld für das Züchten von Tentacula ohne Lizenz",
    "Ein verzauberter Wecker, der einen mit Komplimenten weckt",
    "Ein Glas Drachen-Chili-Soße (extra scharf)",
    "Rückzahlung für den Scherz mit dem Stinksaft in der Großen Halle",
    "Ein magischer Stift, der Hausaufgaben in perfekter Handschrift schreibt",
    "Gebühr für die Mitgliedschaft im Duellierclub (inkl. Pflaster)",
    "Ein Päckchen Zischende Wissbies, um Snape abzulenken",
    "Versicherung gegen Irrwichte, Poltergeister und Peeves",
    "Ein verzauberter Regenschirm, der einen vor Regen und Flüchen schützt",
    "Geld für einen Ausflug nach Hogsmeade (mit extra Butterbier)",
    "Ein verfluchtes Buch, das zurückbeißt (schon wieder)",
    "Kosten für die Beseitigung von Feen aus meinem Garten",
    "Ein Set unsichtbarer Tinte (und der Enthüllungszauber)",
    "Bestellung bei 'Flourish & Blotts' - die schwere Abteilung",
    "Ein persönlicher Hauself für einen Tag (er putzt auch hinter den Ohren)",
    "Anzahlung für eine Harpyie (als Wachvogel)",
    "Ein Kurs in 'Magische Selbstverteidigung gegen aufdringliche Verkäufer'",
    "Ein Dutzend singender Valentinskarten für Filch",
    "Bußgeld für das Verwandeln meines Mitschülers in einen Frettchen",
    "Ein selbst-faltender Papierflieger, der Nachrichten überbringt",
    "Rückerstattung für den 'Glückstrank', der nur Pech gebracht hat",
    "Ein Set magischer Murmeln, die den Weg nach Hause finden",
    "Ein Glas Basiliskengift (für die Unkrautvernichtung)",
    "Beitrag für die 'Rettet die bedrohten magischen Geschöpfe'-Stiftung",
    "Ein verzaubertes Kissen, das einem süße Träume garantiert",
    "Gebühr für die Reinigung des Gemeinschaftsraum-Kamins (zu viel Flohpulver)",
    "Dein Anteil an der 'Kauf Dumbledore einen neuen Hut'-Sammlung",
    "Für die gestrige Runde 'Exploding Snap'",
    "Ein Pfund Drachenleber für den Zaubertrankunterricht",
    "Der Versuch, die Hauspunkte zurückzukaufen",
    "Bestechung der fetten Dame, damit sie uns nach der Sperrstunde reinlässt",
    "Wetteinsatz: Hufflepuff gewinnt den Hauspokal (man darf ja träumen)",
    "Neue Saiten für die Harfe im Mädchenschlafsaal",
    "Rückerstattung für den misslungenen Verwandlungszauber",
    "Ein Set Würg Riegel für die nächste langweilige Unterrichtsstunde",
    "Notfall-Schokofrosch-Lieferung für die Bibliothek",
    "Finanzierung unseres geheimen 'Mitternachts-Snack'-Clubs",
    "Eine Flasche Schrumpflösung, nur für den Fall",
    "Kaution, um Peeves aus der Ritterrüstung zu befreien",
    "Dein Beitrag für das nächste große Feuerwerk von den Weasley-Zwillingen",
    "Ein neues Exemplar von 'Monsterbuch der Monster', das alte hat meinen Finger gegessen",
    "Geld für die Reinigung der Eulerei (schon wieder)",
    "Ein Päckchen Gummischnecken, um Malfoy abzulenken",
    "Nachhilfe in Wahrsagen (bitte keine Todesomen mehr)",
    "Ein selbst-korrigierender Aufsatz für Professor Binns",
    "Die Gebühr für die Apparier-Prüfung (diesmal bestehe ich!)",
    "Eine Runde Butterbier für das gesamte Quidditch-Team",
    "Ein neuer Satz Phiolen, weil Snape meine zerbrochen hat",
    "Ein verzauberter Kompass, der zur Küche von Hogwarts führt",
    "Ein Päckchen 'Fever Fudge', um dem Unterricht zu entgehen",
    "Ein Ticket für den Hogwarts-Express (Sitzplatz am Fenster)",
    "Beitrag für die Dekoration der Großen Halle zu Halloween",
    "Ein neues Set Zauberer-Schachfiguren (die alten sind zu streitlustig)",
    "Ein seltener Alraunen-Setzling für Professor Sprout",
    "Die Reparatur des Besens nach dem Zusammenstoß mit der Peitschenden Weide",
    "Ein Abo für den 'Klitterer', um auf dem Laufenden zu bleiben",
    "Bestechung für einen Hauself für das Passwort zur Küche",
    "Ein neuer Satz Quidditch-Bälle (die Klatscher sind entkommen)",
    "Ein Exemplar von 'Hogwarts, eine Geschichte' (als Einschlafhilfe)",
    "Eine Spende an den Orden des Phönix (pssst!)",
    "Ein neues Paar Drachenleder-Handschuhe für den Kräuterkundeunterricht",
    "Die Kosten für die Entfernung eines Flederwicht-Fluchs",
    "Ein Geschenk für Hagrids neuesten 'harmlosen' Tierfreund",
    "Ein Päckchen Lakritz-Zauberstäbe als Nervennahrung",
    "Der Wetteinsatz, dass Gryffindor das nächste Spiel gewinnt",
    "Ein neuer Umhang (der alte hat einen Trankfleck)",
    "Ein Beitrag für die nächste Sitzung von Dumbledores Armee",
    "Eine Flasche Tinte und eine Rolle Pergament",
    "Ein neues Vorhängeschloss für mein Tagebuch (gegen neugierige Geschwister)",
    "Die Kaution für die Weasley-Zwillinge",
    "Ein Set selbst-schreibender Federn für die ZAG-Vorbereitung",
    "Eine Kiste Kürbispasteten für die ganze Abteilung",
    "Ein Beruhigungstrank für die nächste Begegnung mit dem Minister",
    "Die Reparatur des kaputten Interministeriellen Memos",
    "Ein neues Set Roben für die nächste Gerichtsverhandlung im Zaubergamot",
    "Bestechung für einen besseren Schreibtisch in der Mysteriumsabteilung",
    "Ein Beitrag zur Kaffeekasse der Aurorenzentrale",
    "Ein Päckchen 'U-No-Poo' für Dolores Umbridge",
    "Die Gebühr für die Reinigung der Abteilung für magische Unfälle und Katastrophen",
    "Ein neues Gehirn für die Gehirne in der Halle der Prophezeiungen",
    "Ein Ticket für die nächste Sitzung des Zaubergamots (mit Popcorn)",
    "Ein neues Namensschild für meine Bürotür (diesmal richtig geschrieben)",
    "Ein verzauberter Aktenordner, der sich selbst sortiert",
    "Die Kosten für die Beseitigung eines misslungenen Experiments aus dem Ministerium",
    "Ein Exemplar von 'Die Rechte der magischen Geschöpfe' für die Abteilung zur Führung und Aufsicht Magischer Geschöpfe",
    "Ein neuer Satz Gesetze und Verordnungen (die alten sind verhext)",
    "Ein Beitrag zur 'Wir-ignorieren-den-Minister'-Stiftung",
    "Ein neuer Zeitumkehrer für die Abteilung für Zeitreisen",
    "Ein verzauberter Stift, der Formulare automatisch ausfüllt",
    "Die Reparatur des Lifts im Ministerium (er steckt schon wieder fest)",
    "Ein neues Porträt für das Büro des Ministers (dieses lächelt wenigstens)",
    "Bestechung für eine schnellere Bearbeitung meines Antrags",
    "Ein Päckchen 'Peruanisches Instant-Finsternispulver' für die nächste Besprechung",
    "Ein neuer Satz Prophezeiungen (die alten waren zu deprimierend)",
    "Die Gebühr für die Nutzung des Flohnetzwerks im Ministerium",
    "Ein neuer Schreibtischstuhl, der nicht quietscht",
    "Ein Exemplar von 'Bürokratie für Dummies'",
    "Ein Beitrag zur jährlichen Ministeriums-Weihnachtsfeier",
    "Ein neuer Satz Stempel für die Abteilung für magische Strafverfolgung",
    "Ein verzauberter Kaffeebecher, der nie kalt wird",
    "Die Kosten für die Entfernung eines Poltergeistes aus dem Archiv",
    "Ein neues Gesetzbuch (das alte wurde als Türstopper verwendet)",
    "Ein Beitrag zur 'Macht-Arthur-Weasley-glücklich'-Stiftung",
    "Ein neuer Satz Roben für die nächste internationale Konferenz der Zauberer",
    "Ein verzauberter Papierkorb, der Dokumente sicher vernichtet",
    "Die Reparatur des Springbrunnens im Atrium des Ministeriums",
    "Ein neues Porträt von Cornelius Fudge (zum Draufwerfen)",
    "Bestechung für einen Parkplatz für meinen Besen näher am Eingang",
    "Ein Päckchen 'Kanarienvogel-Kekse' für die Kaffeepause",
    "Ein neuer Satz Aktenvernichter (die alten sind verflucht)",
    "Die Gebühr für die Kalibrierung meines Zauberstabs",
    "Ein neues Exemplar von 'Magische Hieroglyphen und Logogramme'",
    "Ein Beitrag zur 'Wir-brauchen-mehr-Fenster-im-Ministerium'-Initiative",
    "Schweigegeld (du weißt wofür)",
    "Therapiestunde für meine Eule, sie hat eine Existenzkrise",
    "Rückerstattung für den Unsichtbarkeitsumhang, der durchsichtig war",
    "Abonnement für 'Magische Pilze des Monats'-Club",
    "Wöchentliche Lieferung von Drachenatem-Minzbonbons",
    "Investition in ein Startup, das selbstrührende Teetassen herstellt",
    "Bußgeld für das Verzaubern von Muggel-Geld",
    "Anteil an der Schatzsuche in den Verbotenen Wäldern",
    "Kurs 'Wie man mit einem Geist Smalltalk führt'",
    "Schutzgeld für die Kobolde",
    "Ein Pfund gemahlener Einhorn-Hörner (ethisch bezogen, natürlich)",
    "Spende für die 'Anonyme Zaubertrank-Süchtigen'-Hotline",
    "Anzahlung für ein maßgeschneidertes Porträt, das Witze erzählt",
    "Reparatur meines fliegenden Staubsaugers",
    "Gebühr für die Mitgliedschaft im 'Club der exzentrischen Hutträger'",
    "Rückerstattung für das 'Buch der Ruhe', das geschrien hat",
    "Ein Fass Oger-Starkbier",
    "Investition in eine Wurmschwanz-Farm",
    "Dein Anteil an der Wette, wer Professor Binns zum Einschlafen bringt",
    "Ein selbstschreibender Einkaufszettel",
    "Bußgeld für das illegale Züchten von Knallrümpfigen Krötern",
    "Ein verzaubertes Monokel, das die Auren der Menschen anzeigt",
    "Kosten für die professionelle Reinigung meines Denkariums",
    "Ein Set 'Sprechender Socken', die Modetipps geben",
    "Ein Ticket für das jährliche Troll-Ballett",
    "Rückzahlung für den 'Ewigen Kaugummi', der nach drei Minuten den Geschmack verlor",
    "Anzahlung für eine Villa in Little Hangleton (renovierungsbedürftig)",
    "Ein Glas getrockneter Billywig-Stacheln",
    "Dein Gewinn aus dem Zauberer-Bingo letzte Woche",
    "Ein Kurs in 'Die Kunst des dramatischen Auftritts mit Umhang'",
    "Ein Set selbst-nachfüllender Gewürzdosen",
    "Versicherung gegen spontane Verwandlungen",
    "Ein verzaubertes Jo-Jo, das zurückbellt",
    "Gebühr für die Eichung meines moralischen Kompasses",
    "Rückerstattung für die 'Wahrheitsbonbons', die nur Lügen erzählten",
    "Ein Dutzend Flaschen 'Gedächtnis-Lösch-Trank' (für Notfälle)",
    "Investition in eine Kette von mobilen Zaubertrank-Bars",
    "Dein Anteil am Verkauf von 'Gilderoy Lockhart'-Actionfiguren",
    "Ein selbst-malendes Malbuch",
    "Bußgeld für das Verhexen von Parkuhren",
    "Ein verzauberter Brieföffner, der singt, wenn Post kommt",
    "Kosten für die Beseitigung eines Basilisken aus der Kanalisation",
    "Ein Set 'Leuchtender Pilze' für den Garten",
    "Ein Ticket für die 'Magische Weltausstellung'",
    "Rückzahlung für den 'Stimmungsring', der immer nur 'mürrisch' anzeigte",
    "Anzahlung für einen Thestral (du musst ihn nicht sehen können, um zu bezahlen)",
    "Ein Glas Feen-Staub (extra glitzernd)",
    "Dein Gewinn aus der Wette, dass es heute regnet",
    "Ein Kurs in 'Fortgeschrittenes Schweben für Faule'",
    "Ein selbst-deckender Tisch",
    "Versicherung gegen Flüche von Ex-Partnern",
    "Ein verzauberter Blumentopf, der seine Pflanzen selbst aussucht",
    "Gebühr für die jährliche Überprüfung meines Fluchs",
    "Rückerstattung für die 'magischen Bohnen', die nur normale Bohnen waren",
    "Ein Dutzend Flaschen 'Elixier des langen Lebens' (oder auch nur Limonade)",
    "Investition in eine Firma, die selbst-gehende Koffer herstellt",
    "Dein Anteil an der 'Verkaufe-Lockhart-Haarsträhnen'-Aktion",
    "Ein selbst-faltender Zelt für Camping-Abenteuer",
    "Bußgeld für das Verzaubern der Nachbarskatze",
    "Ein verzauberter Kühlschrank, der Rezepte vorschlägt",
    "Kosten für die Exmatrikulation meines Ghuls aus der Abendschule",
    "Ein Set 'sprechender Tierfiguren', die nur die Wahrheit sagen",
    "Ein Ticket für das 'Internationale Symposium für nutzlose Zauber'",
    "Rückzahlung für den 'Gedankenlese-Hut', der nur Kopfschmerzen verursachte",
    "Anzahlung für eine gebrauchte Kristallkugel (mit leichten Kratzern)",
    "Ein Glas Drachen-Tränen (sehr salzig)",
    "Dein Gewinn aus der Wette, wie viele Treppenstufen Hogwarts hat",
    "Ein Kurs in 'Wie man einen Hauself höflich entlässt'",
    "Ein selbst-reinigendes Aquarium",
    "Versicherung gegen den Zorn der Zentauren",
    "Ein verzauberter Besen, der auch Staub wischt",
    "Gebühr für die Namensänderung meines Poltergeistes",
    "Rückerstattung für die 'unsichtbare Tinte', die lila war",
    "Ein Dutzend Flaschen 'Trank des lebenden Todes' (für meine Pflanzen)",
    "Investition in eine Zeitung, die nur gute Nachrichten druckt",
    "Dein Anteil an der 'Verkaufe-gebrauchte-Zauberstäbe'-Börse",
    "Ein selbst-schaukelnder Schaukelstuhl",
    "Bußgeld für das Füttern der Wasserspeier",
    "Ein verzauberter Weinkeller, der den Wein perfekt altern lässt",
    "Kosten für die Umschulung meines Irrwichts (er soll jetzt Komplimente machen)",
    "Ein Set 'singender Pflanzen', die Opernarien schmettern",
    "Ein Ticket für die 'Meisterschaft im Zauberer-Duell'",
    "Rückzahlung für den 'Kraft-Trank', der mich nur müde gemacht hat",
    "Anzahlung für einen Drachen (nur ein kleiner, versprochen)",
    "Ein Glas Phönix-Asche (ideal für den Kamin)",
    "Dein Gewinn aus der Wette, welches Passwort die Fette Dame heute hat",
    "Ein Kurs in 'Wie man sich unsichtbar macht, ohne einen Umhang zu benutzen'",
    "Ein selbst-spielendes Klavier, das nur traurige Lieder kennt",
    "Versicherung gegen Diebstahl durch Niffler",
    "Ein verzauberter Toaster, der Gesichter auf den Toast brennt"
];

export const getRandomPaymentReason = () => {
    return PAYMENT_REASONS[Math.floor(Math.random() * PAYMENT_REASONS.length)];
};
